INSERT INTO tool_capability (
    id, tool_name, display_name, specialty_id, description, input_schema_json, output_schema_json,
    min_role, risk_level, mutability_type, verification_required, snapshot_required, enabled
) VALUES
('tool_get_system_info', 'get_system_info', 'Get System Info', 'sp_system', 'Obtiene informacion general del sistema.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_get_storage_summary', 'get_storage_summary', 'Get Storage Summary', 'sp_system', 'Resume almacenamiento, capacidad y alertas.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_get_os_info', 'get_os_info', 'Get OS Info', 'sp_system', 'Obtiene informacion del sistema operativo.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_get_hostname', 'get_hostname', 'Get Hostname', 'sp_system', 'Obtiene hostname del equipo.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_get_current_user', 'get_current_user', 'Get Current User', 'sp_system', 'Obtiene usuario actual.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_get_uptime', 'get_uptime', 'Get Uptime', 'sp_system', 'Obtiene tiempo de encendido.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_get_cpu_info', 'get_cpu_info', 'Get CPU Info', 'sp_system', 'Obtiene informacion de CPU.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_get_memory_info', 'get_memory_info', 'Get Memory Info', 'sp_system', 'Obtiene informacion de memoria.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_get_disk_info', 'get_disk_info', 'Get Disk Info', 'sp_system', 'Obtiene informacion de discos.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_get_gpu_info', 'get_gpu_info', 'Get GPU Info', 'sp_system', 'Obtiene informacion de GPU.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_get_battery_info', 'get_battery_info', 'Get Battery Info', 'sp_system', 'Obtiene informacion de bateria.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_get_local_ip', 'get_local_ip', 'Get Local IP', 'sp_network', 'Obtiene IP local.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_get_public_ip', 'get_public_ip', 'Get Public IP', 'sp_network', 'Obtiene IP publica.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_get_network_adapters', 'get_network_adapters', 'Get Network Adapters', 'sp_network', 'Lista adaptadores de red.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_get_environment_info', 'get_environment_info', 'Get Environment Info', 'sp_system', 'Obtiene informacion de entorno.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),

('tool_get_cpu_usage', 'get_cpu_usage', 'Get CPU Usage', 'sp_telemetry', 'Uso actual de CPU.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_get_memory_usage', 'get_memory_usage', 'Get Memory Usage', 'sp_telemetry', 'Uso actual de memoria.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_get_disk_usage', 'get_disk_usage', 'Get Disk Usage', 'sp_telemetry', 'Uso actual de disco.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_get_network_usage', 'get_network_usage', 'Get Network Usage', 'sp_telemetry', 'Resumen de uso de red.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_get_top_processes', 'get_top_processes', 'Get Top Processes', 'sp_telemetry', 'Procesos con mayor consumo.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_get_running_services', 'get_running_services', 'Get Running Services', 'sp_telemetry', 'Servicios en ejecucion.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_get_startup_programs', 'get_startup_programs', 'Get Startup Programs', 'sp_telemetry', 'Programas de inicio.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_get_installed_programs', 'get_installed_programs', 'Get Installed Programs', 'sp_telemetry', 'Programas instalados.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_get_windows_updates_status', 'get_windows_updates_status', 'Get Windows Updates Status', 'sp_telemetry', 'Estado de Windows Update.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),

('tool_run_network_diagnostic', 'run_network_diagnostic', 'Run Network Diagnostic', 'sp_network', 'Ejecuta diagnostico de red.', '{}', '{}', 'poweruser', 'r1', 'execute', 1, 0, 1),
('tool_ping_host', 'ping_host', 'Ping Host', 'sp_network', 'Ejecuta ping a un host.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_traceroute_host', 'traceroute_host', 'Traceroute Host', 'sp_network', 'Ejecuta traceroute.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_dns_lookup', 'dns_lookup', 'DNS Lookup', 'sp_network', 'Consulta DNS.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_test_tcp_port', 'test_tcp_port', 'Test TCP Port', 'sp_network', 'Prueba conectividad TCP.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_get_wifi_info', 'get_wifi_info', 'Get WiFi Info', 'sp_network', 'Obtiene informacion WiFi.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_get_default_gateway', 'get_default_gateway', 'Get Default Gateway', 'sp_network', 'Obtiene gateway por defecto.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_get_dns_servers', 'get_dns_servers', 'Get DNS Servers', 'sp_network', 'Obtiene DNS configurados.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_flush_dns_cache', 'flush_dns_cache', 'Flush DNS Cache', 'sp_network', 'Limpia cache DNS.', '{}', '{}', 'poweruser', 'r1', 'execute', 1, 0, 1),
('tool_renew_ip_config', 'renew_ip_config', 'Renew IP Config', 'sp_network', 'Renueva configuracion IP.', '{}', '{}', 'poweruser', 'r2', 'execute', 1, 0, 1),
('tool_release_ip_config', 'release_ip_config', 'Release IP Config', 'sp_network', 'Libera configuracion IP.', '{}', '{}', 'poweruser', 'r2', 'execute', 1, 0, 1),
('tool_reset_network_stack', 'reset_network_stack', 'Reset Network Stack', 'sp_network', 'Resetea el stack de red.', '{}', '{}', 'poweruser', 'r2', 'execute', 1, 1, 1),

('tool_list_processes', 'list_processes', 'List Processes', 'sp_processes', 'Lista procesos activos.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_get_process_detail', 'get_process_detail', 'Get Process Detail', 'sp_processes', 'Detalle de proceso por PID o nombre.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_find_high_cpu_processes', 'find_high_cpu_processes', 'Find High CPU Processes', 'sp_processes', 'Busca procesos con alto CPU.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_find_high_memory_processes', 'find_high_memory_processes', 'Find High Memory Processes', 'sp_processes', 'Busca procesos con alta memoria.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_kill_process', 'kill_process', 'Kill Process', 'sp_processes', 'Termina un proceso.', '{}', '{}', 'poweruser', 'r2', 'execute', 1, 0, 1),
('tool_restart_process', 'restart_process', 'Restart Process', 'sp_processes', 'Reinicia un proceso.', '{}', '{}', 'poweruser', 'r2', 'execute', 1, 0, 1),
('tool_force_kill_process', 'force_kill_process', 'Force Kill Process', 'sp_megaboss', 'Termina un proceso de forma forzada.', '{}', '{}', 'owner', 'r4', 'execute', 1, 1, 1),

('tool_list_services', 'list_services', 'List Services', 'sp_services', 'Lista servicios de Windows.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_get_service_status', 'get_service_status', 'Get Service Status', 'sp_services', 'Obtiene estado de servicio.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_list_running_services', 'list_running_services', 'List Running Services', 'sp_services', 'Lista servicios en ejecucion.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_start_service', 'start_service', 'Start Service', 'sp_services', 'Inicia servicio.', '{}', '{}', 'poweruser', 'r2', 'execute', 1, 0, 1),
('tool_stop_service', 'stop_service', 'Stop Service', 'sp_services', 'Detiene servicio.', '{}', '{}', 'poweruser', 'r2', 'execute', 1, 1, 1),
('tool_restart_service', 'restart_service', 'Restart Service', 'sp_services', 'Reinicia servicio.', '{}', '{}', 'poweruser', 'r2', 'execute', 1, 0, 1),
('tool_enable_service', 'enable_service', 'Enable Service', 'sp_services', 'Habilita servicio.', '{}', '{}', 'poweruser', 'r2', 'execute', 1, 0, 1),
('tool_disable_service', 'disable_service', 'Disable Service', 'sp_services', 'Deshabilita servicio.', '{}', '{}', 'poweruser', 'r3', 'execute', 1, 1, 1),

('tool_analyze_junk', 'analyze_junk', 'Analyze Junk', 'sp_maintenance', 'Analiza archivos temporales.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_run_cleanup', 'run_cleanup', 'Run Cleanup', 'sp_maintenance', 'Ejecuta limpieza controlada.', '{}', '{}', 'poweruser', 'r1', 'execute', 1, 0, 1),
('tool_clean_temp_files', 'clean_temp_files', 'Clean Temp Files', 'sp_maintenance', 'Limpia temporales.', '{}', '{}', 'poweruser', 'r1', 'execute', 1, 0, 1),
('tool_empty_recycle_bin', 'empty_recycle_bin', 'Empty Recycle Bin', 'sp_maintenance', 'Vacia papelera.', '{}', '{}', 'poweruser', 'r1', 'execute', 1, 0, 1),
('tool_run_disk_cleanup', 'run_disk_cleanup', 'Run Disk Cleanup', 'sp_maintenance', 'Ejecuta liberador de espacio.', '{}', '{}', 'poweruser', 'r1', 'execute', 1, 0, 1),
('tool_clear_browser_cache', 'clear_browser_cache', 'Clear Browser Cache', 'sp_maintenance', 'Limpia cache de navegadores.', '{}', '{}', 'poweruser', 'r2', 'execute', 1, 0, 1),
('tool_clear_windows_update_cache', 'clear_windows_update_cache', 'Clear Windows Update Cache', 'sp_maintenance', 'Limpia cache de Windows Update.', '{}', '{}', 'poweruser', 'r2', 'execute', 1, 0, 1),
('tool_check_disk_health', 'check_disk_health', 'Check Disk Health', 'sp_maintenance', 'Revisa salud de disco.', '{}', '{}', 'poweruser', 'r0', 'read', 0, 0, 1),
('tool_scan_system_files', 'scan_system_files', 'Scan System Files', 'sp_maintenance', 'Escaneo SFC.', '{}', '{}', 'poweruser', 'r1', 'execute', 1, 0, 1),
('tool_repair_system_files', 'repair_system_files', 'Repair System Files', 'sp_maintenance', 'Reparacion SFC.', '{}', '{}', 'poweruser', 'r2', 'execute', 1, 1, 1),
('tool_run_dism_health_check', 'run_dism_health_check', 'Run DISM Health Check', 'sp_maintenance', 'Chequeo DISM.', '{}', '{}', 'poweruser', 'r1', 'execute', 1, 0, 1),
('tool_run_dism_restore_health', 'run_dism_restore_health', 'Run DISM Restore Health', 'sp_maintenance', 'Reparacion DISM.', '{}', '{}', 'poweruser', 'r3', 'execute', 1, 1, 1),
('tool_analyze_registry', 'analyze_registry', 'Analyze Registry', 'sp_maintenance', 'Analiza entradas de registro.', '{}', '{}', 'poweruser', 'r0', 'read', 0, 0, 1),
('tool_fix_registry', 'fix_registry', 'Fix Registry', 'sp_sensitive_ops', 'Repara problemas de registro.', '{}', '{}', 'owner', 'r3', 'execute', 1, 1, 1),

('tool_get_firewall_status', 'get_firewall_status', 'Get Firewall Status', 'sp_security', 'Estado del firewall.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_list_firewall_rules', 'list_firewall_rules', 'List Firewall Rules', 'sp_security', 'Lista reglas de firewall.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_get_defender_status', 'get_defender_status', 'Get Defender Status', 'sp_security', 'Estado de Microsoft Defender.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_get_antivirus_status', 'get_antivirus_status', 'Get Antivirus Status', 'sp_security', 'Estado del antivirus.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_get_security_center_status', 'get_security_center_status', 'Get Security Center Status', 'sp_security', 'Estado del Security Center.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_list_open_ports', 'list_open_ports', 'List Open Ports', 'sp_security', 'Lista puertos abiertos.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_list_listening_connections', 'list_listening_connections', 'List Listening Connections', 'sp_security', 'Lista conexiones en escucha.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_list_active_connections', 'list_active_connections', 'List Active Connections', 'sp_security', 'Lista conexiones activas.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_enable_firewall', 'enable_firewall', 'Enable Firewall', 'sp_security', 'Habilita firewall.', '{}', '{}', 'poweruser', 'r3', 'execute', 1, 1, 1),
('tool_disable_firewall', 'disable_firewall', 'Disable Firewall', 'sp_security', 'Deshabilita firewall.', '{}', '{}', 'poweruser', 'r4', 'execute', 1, 1, 1),
('tool_run_defender_quick_scan', 'run_defender_quick_scan', 'Run Defender Quick Scan', 'sp_security', 'Lanza escaneo rapido de Defender.', '{}', '{}', 'poweruser', 'r1', 'execute', 1, 0, 1),
('tool_run_defender_full_scan', 'run_defender_full_scan', 'Run Defender Full Scan', 'sp_security', 'Lanza escaneo completo de Defender.', '{}', '{}', 'poweruser', 'r2', 'execute', 1, 0, 1),

('tool_list_devices', 'list_devices', 'List Devices', 'sp_drivers', 'Lista dispositivos.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_list_problem_devices', 'list_problem_devices', 'List Problem Devices', 'sp_drivers', 'Lista dispositivos con problema.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_get_device_detail', 'get_device_detail', 'Get Device Detail', 'sp_drivers', 'Detalle de dispositivo.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_get_driver_info', 'get_driver_info', 'Get Driver Info', 'sp_drivers', 'Informacion de driver.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_update_driver', 'update_driver', 'Update Driver', 'sp_drivers', 'Actualiza driver.', '{}', '{}', 'poweruser', 'r2', 'execute', 1, 0, 1),
('tool_open_optional_driver_updates', 'open_optional_driver_updates', 'Open Optional Driver Updates', 'sp_drivers', 'Abre updates opcionales de drivers.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_rescan_devices', 'rescan_devices', 'Rescan Devices', 'sp_drivers', 'Reescanea dispositivos.', '{}', '{}', 'poweruser', 'r1', 'execute', 1, 0, 1),

('tool_list_directory', 'list_directory', 'List Directory', 'sp_filesystem', 'Lista archivos y carpetas.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_read_file', 'read_file', 'Read File', 'sp_filesystem', 'Lee archivo de texto.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_get_file_info', 'get_file_info', 'Get File Info', 'sp_filesystem', 'Informacion de archivo.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_search_files', 'search_files', 'Search Files', 'sp_filesystem', 'Busca archivos.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_calculate_folder_size', 'calculate_folder_size', 'Calculate Folder Size', 'sp_filesystem', 'Calcula tamano de carpeta.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_write_file', 'write_file', 'Write File', 'sp_filesystem', 'Escribe archivo.', '{}', '{}', 'owner', 'r3', 'execute', 1, 1, 1),
('tool_create_folder', 'create_folder', 'Create Folder', 'sp_filesystem', 'Crea carpeta.', '{}', '{}', 'viewer', 'r1', 'execute', 1, 0, 1),
('tool_delete_file', 'delete_file', 'Delete File', 'sp_filesystem', 'Elimina archivo.', '{}', '{}', 'viewer', 'r3', 'execute', 1, 1, 1),
('tool_move_file', 'move_file', 'Move File', 'sp_filesystem', 'Mueve archivo.', '{}', '{}', 'viewer', 'r2', 'execute', 1, 1, 1),
('tool_copy_file', 'copy_file', 'Copy File', 'sp_filesystem', 'Copia archivo.', '{}', '{}', 'viewer', 'r1', 'execute', 1, 0, 1),
('tool_rename_file', 'rename_file', 'Rename File', 'sp_filesystem', 'Renombra archivo.', '{}', '{}', 'viewer', 'r1', 'execute', 1, 0, 1),
('tool_force_delete_file', 'force_delete_file', 'Force Delete File', 'sp_megaboss', 'Elimina archivo de forma forzada.', '{}', '{}', 'owner', 'r4', 'execute', 1, 1, 1),

('tool_read_event_logs', 'read_event_logs', 'Read Event Logs', 'sp_audit', 'Lee event logs.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_read_system_log', 'read_system_log', 'Read System Log', 'sp_audit', 'Lee log de sistema.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_read_application_log', 'read_application_log', 'Read Application Log', 'sp_audit', 'Lee log de aplicaciones.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_read_security_log', 'read_security_log', 'Read Security Log', 'sp_audit', 'Lee log de seguridad.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_export_event_logs', 'export_event_logs', 'Export Event Logs', 'sp_audit', 'Exporta event logs.', '{}', '{}', 'viewer', 'r1', 'read', 0, 0, 1),
('tool_get_kernelia_audit_log', 'get_kernelia_audit_log', 'Get KernelIA Audit Log', 'sp_audit', 'Lee auditoria de KernelIA.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_search_kernelia_audit_log', 'search_kernelia_audit_log', 'Search KernelIA Audit Log', 'sp_audit', 'Busca en auditoria.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),

('tool_get_power_plan', 'get_power_plan', 'Get Power Plan', 'sp_performance', 'Obtiene plan de energia.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_list_power_plans', 'list_power_plans', 'List Power Plans', 'sp_performance', 'Lista planes de energia.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_get_sleep_settings', 'get_sleep_settings', 'Get Sleep Settings', 'sp_performance', 'Obtiene configuracion de suspension.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_get_startup_impact', 'get_startup_impact', 'Get Startup Impact', 'sp_performance', 'Analiza impacto de inicio.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_set_power_plan', 'set_power_plan', 'Set Power Plan', 'sp_performance', 'Cambia plan de energia.', '{}', '{}', 'poweruser', 'r2', 'execute', 1, 0, 1),
('tool_set_sleep_settings', 'set_sleep_settings', 'Set Sleep Settings', 'sp_performance', 'Cambia suspension.', '{}', '{}', 'poweruser', 'r2', 'execute', 1, 0, 1),
('tool_optimize_startup_apps', 'optimize_startup_apps', 'Optimize Startup Apps', 'sp_performance', 'Optimiza apps de inicio.', '{}', '{}', 'poweruser', 'r2', 'execute', 1, 0, 1),

('tool_list_installed_apps', 'list_installed_apps', 'List Installed Apps', 'sp_software', 'Lista aplicaciones instaladas.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_get_app_detail', 'get_app_detail', 'Get App Detail', 'sp_software', 'Detalle de aplicacion.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_check_app_updates', 'check_app_updates', 'Check App Updates', 'sp_software', 'Revisa actualizaciones de apps.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_list_windows_features', 'list_windows_features', 'List Windows Features', 'sp_software', 'Lista features de Windows.', '{}', '{}', 'viewer', 'r0', 'read', 0, 0, 1),
('tool_uninstall_app', 'uninstall_app', 'Uninstall App', 'sp_software', 'Desinstala una aplicacion.', '{}', '{}', 'poweruser', 'r3', 'execute', 1, 1, 1),
('tool_enable_windows_feature', 'enable_windows_feature', 'Enable Windows Feature', 'sp_software', 'Habilita feature de Windows.', '{}', '{}', 'poweruser', 'r3', 'execute', 1, 1, 1),
('tool_disable_windows_feature', 'disable_windows_feature', 'Disable Windows Feature', 'sp_software', 'Deshabilita feature de Windows.', '{}', '{}', 'poweruser', 'r3', 'execute', 1, 1, 1),

('tool_secure_terminal', 'secure_terminal', 'Secure Terminal', 'sp_sensitive_ops', 'Ejecuta comando validado.', '{}', '{}', 'owner', 'r4', 'execute', 1, 1, 1),
('tool_run_shell_command', 'run_shell_command', 'Run Shell Command', 'sp_sensitive_ops', 'Ejecuta shell command.', '{}', '{}', 'owner', 'r4', 'execute', 1, 1, 1),
('tool_run_powershell_command', 'run_powershell_command', 'Run PowerShell Command', 'sp_sensitive_ops', 'Ejecuta comando PowerShell.', '{}', '{}', 'owner', 'r4', 'execute', 1, 1, 1),
('tool_edit_registry_key', 'edit_registry_key', 'Edit Registry Key', 'sp_sensitive_ops', 'Edita clave de registro.', '{}', '{}', 'owner', 'r4', 'execute', 1, 1, 1),
('tool_delete_registry_key', 'delete_registry_key', 'Delete Registry Key', 'sp_sensitive_ops', 'Elimina propiedad de registro.', '{}', '{}', 'owner', 'r4', 'execute', 1, 1, 1),
('tool_reboot_system', 'reboot_system', 'Reboot System', 'sp_sensitive_ops', 'Reinicia el sistema.', '{}', '{}', 'owner', 'r4', 'execute', 1, 1, 1),
('tool_shutdown_system', 'shutdown_system', 'Shutdown System', 'sp_sensitive_ops', 'Apaga el sistema.', '{}', '{}', 'owner', 'r4', 'execute', 1, 1, 1),
('tool_run_elevated_command', 'run_elevated_command', 'Run Elevated Command', 'sp_megaboss', 'Ejecuta comando elevado.', '{}', '{}', 'owner', 'r4', 'execute', 1, 1, 1),
('tool_modify_system_registry', 'modify_system_registry', 'Modify System Registry', 'sp_megaboss', 'Modifica registro del sistema.', '{}', '{}', 'owner', 'r4', 'execute', 1, 1, 1),
('tool_disable_security_component', 'disable_security_component', 'Disable Security Component', 'sp_megaboss', 'Deshabilita componente de seguridad.', '{}', '{}', 'owner', 'r4', 'execute', 1, 1, 1),
('tool_enable_security_component', 'enable_security_component', 'Enable Security Component', 'sp_megaboss', 'Habilita componente de seguridad.', '{}', '{}', 'owner', 'r4', 'execute', 1, 1, 1),
('tool_execute_admin_script', 'execute_admin_script', 'Execute Admin Script', 'sp_megaboss', 'Ejecuta script administrativo.', '{}', '{}', 'owner', 'r4', 'execute', 1, 1, 1)
ON CONFLICT(id) DO NOTHING;

INSERT INTO risk_policy (
    id, tool_name, risk_level, min_role, requires_snapshot, requires_post_verify, requires_megaboss, allow_auto_execute
) VALUES
('risk_ping_host', 'ping_host', 'r0', 'viewer', 0, 0, 0, 1),
('risk_dns_lookup', 'dns_lookup', 'r0', 'viewer', 0, 0, 0, 1),
('risk_get_service_status', 'get_service_status', 'r0', 'viewer', 0, 0, 0, 1),
('risk_run_network_diagnostic', 'run_network_diagnostic', 'r1', 'poweruser', 0, 1, 0, 1),
('risk_flush_dns_cache', 'flush_dns_cache', 'r1', 'poweruser', 0, 1, 0, 1),
('risk_reset_network_stack', 'reset_network_stack', 'r2', 'poweruser', 1, 1, 0, 0),
('risk_kill_process', 'kill_process', 'r2', 'poweruser', 0, 1, 0, 0),
('risk_restart_service', 'restart_service', 'r2', 'poweruser', 0, 1, 0, 0),
('risk_disable_service', 'disable_service', 'r3', 'poweruser', 1, 1, 0, 0),
('risk_repair_system_files', 'repair_system_files', 'r2', 'poweruser', 1, 1, 0, 0),
('risk_run_dism_restore_health', 'run_dism_restore_health', 'r3', 'poweruser', 1, 1, 0, 0),
('risk_write_file', 'write_file', 'r3', 'owner', 1, 1, 0, 0),
('risk_delete_file', 'delete_file', 'r3', 'viewer', 1, 1, 0, 0),
('risk_uninstall_app', 'uninstall_app', 'r3', 'poweruser', 1, 1, 0, 0),
('risk_enable_windows_feature', 'enable_windows_feature', 'r3', 'poweruser', 1, 1, 0, 0),
('risk_disable_windows_feature', 'disable_windows_feature', 'r3', 'poweruser', 1, 1, 0, 0),
('risk_run_shell_command', 'run_shell_command', 'r4', 'owner', 1, 1, 0, 0),
('risk_run_powershell_command', 'run_powershell_command', 'r4', 'owner', 1, 1, 0, 0),
('risk_reboot_system', 'reboot_system', 'r4', 'owner', 1, 1, 0, 0),
('risk_shutdown_system', 'shutdown_system', 'r4', 'owner', 1, 1, 0, 0),
('risk_run_elevated_command', 'run_elevated_command', 'r4', 'owner', 1, 1, 1, 0),
('risk_force_kill_process', 'force_kill_process', 'r4', 'owner', 1, 1, 1, 0),
('risk_force_delete_file', 'force_delete_file', 'r4', 'owner', 1, 1, 1, 0),
('risk_disable_security_component', 'disable_security_component', 'r4', 'owner', 1, 1, 1, 0)
ON CONFLICT(id) DO NOTHING;

INSERT INTO tool_postcondition (id, tool_id, verify_tool_name, verify_args_json, expected_condition) VALUES
('post_run_network_diagnostic', 'tool_run_network_diagnostic', 'run_network_diagnostic', '{}', 'diagnostic_completed'),
('post_flush_dns_cache', 'tool_flush_dns_cache', 'dns_lookup', '{"host":"example.com"}', 'dns_resolution_available'),
('post_restart_service', 'tool_restart_service', 'get_service_status', '{"name":"<service_name>"}', 'service_running'),
('post_kill_process', 'tool_kill_process', 'get_process_detail', '{"pid":"<pid>"}', 'process_not_found'),
('post_run_cleanup', 'tool_run_cleanup', 'analyze_junk', '{}', 'recoverable_space_reduced'),
('post_run_defender_quick_scan', 'tool_run_defender_quick_scan', 'get_defender_status', '{}', 'scan_registered')
ON CONFLICT(id) DO NOTHING;

INSERT INTO tool_guardrail (id, tool_id, guardrail_code, guardrail_description) VALUES
('guard_reset_network_stack', 'tool_reset_network_stack', 'SNAPSHOT_REQUIRED', 'Reseteo de stack requiere snapshot previo.'),
('guard_disable_service', 'tool_disable_service', 'CRITICAL_SERVICE_REVIEW', 'No deshabilitar servicios criticos sin validacion adicional.'),
('guard_write_file', 'tool_write_file', 'SENSITIVE_PATH_REVIEW', 'Escritura en rutas sensibles debe revisarse.'),
('guard_force_delete_file', 'tool_force_delete_file', 'MEGABOSS_ONLY', 'Borrado forzado solo bajo MegaBoss.'),
('guard_disable_security_component', 'tool_disable_security_component', 'DUAL_CONTROL', 'Cambios de seguridad requieren control dual.')
ON CONFLICT(id) DO NOTHING;
